version: '3'

services:
  website-admin:
    image: nginx:latest
    depends_on:
      - user
    ports:
      - "8080:80"
    volumes:
      - ./admin/dist:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

  website-client:
    image: nginx:latest
    depends_on:
      - user
    ports:
      - "80:80"
    volumes:
      - ./client/dist:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

  user:
    build: ./users-service
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    volumes:
      - ./users-service:/usr/src/app
    ports:
      - 5001:5001

  product:
    build: ./products-service
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    volumes:
      - ./products-service:/usr/src/app
    ports:
      - 5002:5002

  venta:
    build: ./ventas-service
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    volumes:
      - ./ventas-service:/usr/src/app
    ports:
      - 5003:5003

  detalle:
    build: ./detalles-service
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    volumes:
      - ./detalles-service:/usr/src/app
    ports:
      - 5004:5004
  
  farmabot:
    build: ./farmabot
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    volumes:
      - ./farmabot:/usr/src/app
    ports:
      - 5000:5000

  db:
    build: ./db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: "exit 0"
    ports:
      - 3306:3306
