version: '3'

services: 
  website:
    image: nginx:latest
    depends_on: 
      - user
    ports:
      - "80:80"
    volumes:
      - ./client:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    

  user:
    build: ./users-service
    depends_on: 
      - db
    environment: 
      - DATABASE_HOST=db
    volumes:
      - ./users-service:/usr/src/app
    ports: 
      - 5001:5001

  db:
    build: ./db
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: "exit 0"
    ports:
      - 3306:3306