INSERT INTO PRODUCTO(nombre,precio,stock) VALUES ('DICLOFENACO SODICO',1.5,20);
INSERT INTO PRODUCTO(nombre,precio,stock) VALUES ('CLOBETASOL',1.0,30);
INSERT INTO PRODUCTO(nombre,precio,stock) VALUES ('AMOXICILINA',1.2,25);
INSERT INTO PRODUCTO(nombre,precio,stock) VALUES ('SALBUTAMOL',2.5,22);
INSERT INTO PRODUCTO(nombre,precio,stock) VALUES ('PARACETAMOL',1.0,30);
INSERT INTO PRODUCTO(nombre,precio,stock) VALUES ('CORTIFLEX',3.5,15);
